# pubspec.yaml (Versión con las dependencias más recientes)
name: tu_recorrido
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Firebase packages
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  package_info_plus: ^8.0.0

  # Location / maps / auth
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.0
  google_sign_in: ^6.3.0
  http: ^1.2.1
  geolocator_web: ^4.1.3

  # UI / utilities
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  flutter_polyline_points: ^3.1.0
  shadcn_flutter: ^0.0.44
  flex_color_scheme: ^8.3.0
  shadcn_ui: ^0.38.1

  #Para el emulador de dispositivos
  device_preview: ^1.3.1

  # La librería 'js' ha sido eliminada. Si tu código la requiere, puedes re-añadirla.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Últimas reglas de lints
  

flutter:
  uses-material-design: true

  assets:
    - assets/img/    #esto importa todas las imágenes de la carpeta img